_commit: ea3be8a
_src_path: gh:bswck/skeleton
author_username: bswck
docs: true
docs_slug: manifests
email_address: bswck.dev@gmail.com
github_username: bswck
license_name: MIT
org_full_name: Bartosz Sławecki
package_name: manifests
project_description: Generate code from JSON manifests.
publish_on_pypi: true
pypi_project_description: Generate code from JSON manifests.
pypi_project_name: manifests
python_version: '3.8'
repo_name: manifests
test_suite: true
use_precommit: true
visibility: public
